### PR TITLE
Redirect to reminders on home page

### LINKED ISSUE #2: Reroute to Reminders
When the user visits the root of the application, they should be redirected to `'/reminders'` and should see a list of all reminders on the page. This means making a hopefully small adjustment to your `router.js` file.  

**Hot Tip**: This will make your previous test fail (if you had it passing). Make the necessary changes in the test(s).

### PR DESCRIPTION
**Pull request by gness1804**
## Purpose

The user is redirected to the /reminders route when visiting the home page. 

Closes #2 

## Approach

This reroutes the user and also cleans up the appearance of the reminders on the page.

### CODE REVIEW

File: app/router.js [hunk 1]
```diff
@@ -7,7 +7,8 @@ const Router = Ember.Router.extend({
 });
 
 Router.map(function() {
-  this.route('reminders', {path: '/'});
+  this.route('root', {path: '/'});
```
Comment (nfosterky) [inline app/router.js]: This route is unnecessary, please remove

File: app/routes/root.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+  beforeModel(){
+    this.transitionTo('reminders');
```
Comment (nfosterky) [inline app/routes/root.js]: change the name of this file to index.js, this will be the default 'root' of your app.
https://guides.emberjs.com/v2.10.0/routing/defining-your-routes/#toc_index-routes
